### ISSUE TITLE
Non Standard Port

### ISSUE THREAD

**Issue by smikulski** [sematext/rsyslog#1]
hello

it is possible to add non standard port declaration ? 
Like 
http://www.rsyslog.com/doc/ommysql.html

"serverport"

Configuration with cluster of many PG on one machine is comon this days.

Best

**Comment by radu-gheorghe** [comment]
Hello,

You need a non standard port for an output or for an input. And which one? It looks like ommysql already supports it.

Either way, please ask questions on the rsyslog mailing list here: http://lists.adiscon.net/mailman/listinfo/rsyslog

For rsyslog bug reports, check out the project page, this is just a fork:
https://github.com/rsyslog/rsyslog

Best regards,
Radu
